using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using rPDU2MQTT.Classes;
using rPDU2MQTT.Models.Config;
using YamlDotNet.Serialization;

namespace rPDU2MQTT.Services.Gui;

/// <summary>
/// Describes a single configuration field so the GUI can render a typed input for it.
/// The schema is generated by reflecting over the <see cref="Config"/> model and its
/// YAML/Display/validation attributes, so it stays in sync with the model automatically.
/// </summary>
public sealed class SchemaNode
{
    public string Key { get; set; } = "";
    public string Label { get; set; } = "";
    public string? Description { get; set; }
    public string Type { get; set; } = "string";
    public bool Required { get; set; }
    public object? Default { get; set; }
    public double? Min { get; set; }
    public double? Max { get; set; }
    public string[]? EnumValues { get; set; }

    /// <summary>
    /// The choices in <see cref="EnumValues"/> were discovered from the running host, not declared on the
    /// model — today the time zones it can resolve.
    ///
    /// <para>
    /// They are a GUI convenience and must never become a *constraint*: baking one machine's tzdata into the
    /// CRD would have the API server reject a zone that is perfectly valid on the cluster actually running
    /// the workload, and the emitted CRD would differ per build machine. Consumers that validate — the CRD
    /// generator — skip the enum and keep the plain type; consumers that only offer choices render as usual.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool DynamicChoices { get; set; }

    /// <summary>
    /// Why the GUI shows this setting but won't let you change it — see <c>NotEditableInGuiAttribute</c>.
    /// Null when the field is editable as normal.
    /// </summary>
    public string? NotEditableReason { get; set; }

    /// <summary>
    /// This setting is the on/off switch for a whole capability — see <c>FeatureToggleAttribute</c>. The GUI
    /// gathers these onto one Features page and omits them from the section's own form.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsFeatureToggle { get; set; }

    /// <summary>
    /// This setting only applies when a sibling setting has one of these values — see
    /// <c>VisibleWhenAttribute</c>. The GUI hides it the rest of the time. Null when it always applies.
    /// </summary>
    public VisibleWhenRule? VisibleWhen { get; set; }
    /// <summary>
    /// This list holds tag names, so the GUI offers the tags the configuration already defines instead of a
    /// free-text box per entry — see <c>TagChoicesAttribute</c>. A tag is free-form and typed where it is
    /// defined; naming one here is a reference, and a typo in a reference matches nothing at all.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool TagChoices { get; set; }

    /// <summary>
    /// This section belongs to an externally loaded plugin, so it is stored under <c>Config.Plugins</c>
    /// rather than as a property of its own. The GUI reads and writes it there.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public bool IsPlugin { get; set; }

    public string[]? TemplateVars { get; set; }
    public List<SchemaNode>? Properties { get; set; }
    public SchemaNode? ValueSchema { get; set; }
    public string? KeyType { get; set; }
}

/// <summary>When a setting applies: the sibling property that decides, and the values it applies to.</summary>
public class VisibleWhenRule
{
    public string Key { get; set; } = "";
    public string[] Values { get; set; } = [];
}

/// <summary>
/// Reflection-based schema generation plus JSON/YAML round-tripping for the configuration GUI.
/// </summary>
public static class ConfigSchema
{
    // Used for the schema and status/test payloads (the frontend reads camelCase keys).
    public static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() },
    };

    // Used for the config payload itself. Keys are the model's real (PascalCase) property names so
    // they line up exactly with the schema's Key values the form binds against.
    /// <summary>The options the config payload itself round-trips through. Exposed so anything comparing two
    /// configuration documents (see <see cref="ConfigApply"/>) uses the same field names the GUI binds to.</summary>
    public static JsonSerializerOptions ConfigJsonOptions => ConfigJson;

    private static readonly JsonSerializerOptions ConfigJson = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    /// <summary>
    /// The metrics a live source may be bound to — read from <c>EnergyFlowSource.Metric</c>, which is what
    /// actually validates a binding.
    ///
    /// <para>
    /// Not every metric in the unit table: <c>energytoday</c> is derived by the aggregation service from a
    /// counter's rise, so offering it as something to bind would produce a binding the source validation
    /// then rejects. Taken from the property rather than retyped so the offer and the rule cannot drift.
    /// </para>
    /// </summary>
    private static readonly string[] BindableMetrics =
        typeof(EnergyFlowSource).GetProperty(nameof(EnergyFlowSource.Metric))!
            .GetCustomAttribute<AllowedValuesAttribute>()!.Values
            .Select(v => v?.ToString() ?? "").ToArray();

    /// <summary>Build the schema for the whole configuration model.</summary>
    public static List<SchemaNode> Build() => BuildObject(typeof(Config));

    /// <summary>
    /// The schema, plus a section per externally loaded plugin.
    ///
    /// <para>
    /// This is what makes a runtime-loaded plugin configurable without shipping any UI: the GUI's form is
    /// drawn from whatever this returns, so a plugin's settings class becomes a rendered page with typed
    /// inputs, descriptions and defaults — the same treatment a built-in section gets.
    /// </para>
    /// <para>
    /// The CRD generator deliberately calls <see cref="Build()"/> instead. A CRD is a compile-time contract
    /// published to the API server; it cannot describe a type that only exists on one operator's machine,
    /// and generating a different CRD per install is worse than not describing those fields at all.
    /// </para>
    /// </summary>
    public static List<SchemaNode> Build(IEnumerable<(string Id, string Label, Type ConfigType)> plugins)
    {
        var schema = BuildObject(typeof(Config));
        foreach (var (id, label, type) in plugins)
        {
            var node = new SchemaNode
            {
                Key = id,
                Label = label,
                Type = "object",
                Description = "Settings for the " + label + " plugin.",
                Properties = BuildObject(type),
                IsPlugin = true,
            };
            schema.Add(node);
        }
        return schema;
    }

    private static List<SchemaNode> BuildObject(Type type)
    {
        var nodes = new List<SchemaNode>();
        foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!prop.CanRead || !prop.CanWrite)
                continue;

            // Skip properties hidden from JSON (e.g. back-compat aliases) so they don't show in the GUI.
            if (prop.GetCustomAttribute<JsonIgnoreAttribute>() is not null)
                continue;

            nodes.Add(BuildNode(prop));
        }
        return nodes;
    }

    private static SchemaNode BuildNode(PropertyInfo prop)
    {
        var type = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;

        var node = new SchemaNode
        {
            // Key drives the JSON payload + the CR spec; align it with [JsonPropertyName] so the GUI
            // JSON, the Kubernetes CR spec, and the YAML config all share one field vocabulary.
            Key = prop.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? prop.Name,
            // Friendly display title for the GUI: [Display(Name)] wins, else the YAML alias / property name.
            Label = prop.GetCustomAttribute<DisplayAttribute>()?.Name
                ?? prop.GetCustomAttribute<YamlMemberAttribute>()?.Alias
                ?? prop.Name,
            Description = ResolveDescription(prop),
            Required = prop.GetCustomAttribute<RequiredAttribute>() is not null,
        };

        if (prop.GetCustomAttribute<RangeAttribute>() is { } range)
        {
            node.Min = ToDouble(range.Minimum);
            node.Max = ToDouble(range.Maximum);
        }

        if (prop.GetCustomAttribute<DefaultValueAttribute>()?.Value is { } dv)
            node.Default = dv;

        if (prop.GetCustomAttribute<TemplateVariablesAttribute>() is { } tv)
            node.TemplateVars = tv.Names;

        // A setting whose "off" would remove the means of turning it back on. Carried on the schema so the
        // form does not need its own hardcoded list of which fields those are.
        if (prop.GetCustomAttribute<NotEditableInGuiAttribute>() is { } locked)
            node.NotEditableReason = locked.Reason;

        // The switch that turns a whole capability on or off, gathered onto the GUI's Features page. Declared
        // on the model because the names differ (Enabled, DiscoveryEnabled, Exporter) and a form-side rule
        // guessing from the name would quietly drop the ones that don't match.
        if (prop.GetCustomAttribute<FeatureToggleAttribute>() is not null)
            node.IsFeatureToggle = true;

        // A setting that belongs to one choice of another setting — the Prometheus URL when the history
        // provider is Prometheus. The form hides it otherwise.
        if (prop.GetCustomAttribute<VisibleWhenAttribute>() is { } vis)
            node.VisibleWhen = new VisibleWhenRule { Key = vis.Key, Values = vis.Values };

        // A string with a fixed set of choices ([AllowedValues]) renders as a dropdown, not free text (#176).
        // An optional one keeps a leading blank choice so it can be cleared back to "unset" (auto).
        if (type == typeof(string) && prop.GetCustomAttribute<AllowedValuesAttribute>() is { } allowed)
        {
            var values = allowed.Values.Select(v => v?.ToString() ?? string.Empty);
            node.EnumValues = (node.Required ? values : values.Prepend(string.Empty)).ToArray();
            node.Type = "enum";
            return node;
        }

        // Choices that only the running host knows — the time zones it can resolve. Same dropdown as
        // [AllowedValues], but filled in here because the list is host-dependent (see TimeZoneChoicesAttribute).
        // Blank stays first so the field can be cleared back to "use the host's zone".
        if (type == typeof(string) && prop.GetCustomAttribute<TimeZoneChoicesAttribute>() is not null)
        {
            node.EnumValues = Core.Flow.EnergyPeriod.AvailableZones().Prepend(string.Empty).ToArray();
            node.DynamicChoices = true;
            node.Type = "enum";
            return node;
        }

        node.Type = ClassifyAndPopulate(type, prop.Name, node);

        // A closed set of answers for a collection's items. The element of a list and the value of a
        // dictionary have no property to annotate, so this is where their choices arrive.
        if (node.ValueSchema is { } vs)
        {
            if (prop.GetCustomAttribute<ItemAllowedValuesAttribute>() is { } items)
            {
                vs.EnumValues = items.Values;
                vs.Type = "enum";
            }
            else if (prop.GetCustomAttribute<MetricItemChoicesAttribute>() is not null)
            {
                vs.EnumValues = BindableMetrics;
                vs.Type = "enum";
            }
            else if (prop.GetCustomAttribute<TagChoicesAttribute>() is not null)
            {
                // Not an enum: the choices come from the document being edited, which the server has no
                // opinion on. The flag says "these are tags"; the GUI reads the tags it already holds.
                node.TagChoices = true;
            }
        }
        return node;
    }

    private static string ClassifyAndPopulate(Type type, string name, SchemaNode node)
    {
        if (type == typeof(string))
            return name.Contains("password", StringComparison.OrdinalIgnoreCase) || name.Contains("secret", StringComparison.OrdinalIgnoreCase)
                ? "password" : "string";

        if (type == typeof(bool)) return "bool";
        if (type == typeof(int) || type == typeof(long) || type == typeof(short)) return "int";
        if (type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "double";

        if (type.IsEnum)
        {
            node.EnumValues = Enum.GetNames(type);
            return "enum";
        }

        // Dictionary<TKey, TValue> -> a map of editable rows.
        var dict = type.GetInterfaces().Concat([type])
            .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>));
        if (dict is not null)
        {
            var args = dict.GetGenericArguments();
            node.KeyType = args[0] == typeof(string) ? "string" : "int";
            node.ValueSchema = BuildValueSchema(args[1]);
            return "dictionary";
        }

        // List/array of objects or scalars.
        if (type != typeof(string) && typeof(IEnumerable).IsAssignableFrom(type))
        {
            var elem = type.IsArray ? type.GetElementType()! : type.GetGenericArguments().FirstOrDefault();
            if (elem is not null)
            {
                node.ValueSchema = BuildValueSchema(elem);
                return "list";
            }
        }

        // Nested settings object.
        node.Properties = BuildObject(type);
        return "object";
    }

    private static SchemaNode BuildValueSchema(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        var node = new SchemaNode { Key = "", Label = "" };
        node.Type = ClassifyAndPopulate(type, "", node);
        return node;
    }

    private static string? ResolveDescription(PropertyInfo prop)
        => prop.GetCustomAttribute<YamlMemberAttribute>()?.Description
        ?? prop.GetCustomAttribute<DisplayAttribute>()?.Description
        ?? prop.GetCustomAttribute<DescriptionAttribute>()?.Description;

    private static double? ToDouble(object? value)
        => value is null ? null : Convert.ToDouble(value);

    /// <summary>Serialize the live config to JSON for the form to bind against.</summary>
    public static string ToJson(Config config) => JsonSerializer.Serialize(config, ConfigJson);

    /// <summary>Deserialize the form's JSON back into a config object.</summary>
    public static Config FromJson(string json)
        => JsonSerializer.Deserialize<Config>(json, ConfigJson) ?? throw new Exception("Configuration payload was empty.");

    /// <summary>
    /// Return a deep copy with secrets stripped, for writing to a Kubernetes CR or exporting a manifest
    /// (credentials belong in a Secret, not the CR spec / committed manifest).
    /// </summary>
    public static Config RedactSecrets(Config config)
    {
        var clone = FromJson(ToJson(config));
        clone.MQTT.Credentials = null;
        foreach (var instance in clone.Pdus.Values)
            instance.Credentials = null;
        clone.EmonCMS.ApiKey = null;
        clone.Gui.Password = null;
        if (clone.Gui.Oidc is not null)
            clone.Gui.Oidc.ClientSecret = null;
        clone.Api.ApiKey = null;
        return clone;
    }

    /// <summary>Serialize a config object to YAML (honoring the model's YAML aliases).</summary>
    public static string ToYaml(Config config)
    {
        var serializer = new SerializerBuilder()
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .WithQuotingNecessaryStrings()
            .Build();
        return serializer.Serialize(config);
    }
}
