apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rpdu2mqtt.fullname" . }}
  labels:
    {{- include "rpdu2mqtt.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
