{{- if and (not .Values.existingSecret) (include "rpdu2mqtt.hasSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rpdu2mqtt.fullname" . }}
  labels:
    {{- include "rpdu2mqtt.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.credentials.mqtt.username }}
  RPDU2MQTT_MQTT_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.credentials.mqtt.password }}
  RPDU2MQTT_MQTT_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.credentials.pdu.username }}
  RPDU2MQTT_PDU_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.credentials.pdu.password }}
  RPDU2MQTT_PDU_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.credentials.emoncmsApiKey }}
  RPDU2MQTT_EMONCMS_APIKEY: {{ . | quote }}
  {{- end }}
{{- end }}
