{{- if and (dig "Gui" "Enabled" false .Values.config) .Values.service.gui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpdu2mqtt.fullname" . }}-gui
  labels:
    {{- include "rpdu2mqtt.labels" . | nindent 4 }}
  {{- with .Values.service.gui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.gui.type }}
  selector:
    {{- include "rpdu2mqtt.selectorLabels" . | nindent 4 }}
  ports:
    - name: gui
      port: {{ dig "Gui" "Port" 8080 .Values.config }}
      targetPort: gui
{{- end }}
