using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using rPDU2MQTT.Classes;
using rPDU2MQTT.Models.Config;
using YamlDotNet.Serialization;

namespace rPDU2MQTT.Services.Gui;

/// <summary>
/// Describes a single configuration field so the GUI can render a typed input for it.
/// The schema is generated by reflecting over the <see cref="Config"/> model and its
/// YAML/Display/validation attributes, so it stays in sync with the model automatically.
/// </summary>
public sealed class SchemaNode
{
    public string Key { get; set; } = "";
    public string Label { get; set; } = "";
    public string? Description { get; set; }
    public string Type { get; set; } = "string";
    public bool Required { get; set; }
    public object? Default { get; set; }
    public double? Min { get; set; }
    public double? Max { get; set; }
    public string[]? EnumValues { get; set; }
    public string[]? TemplateVars { get; set; }
    public List<SchemaNode>? Properties { get; set; }
    public SchemaNode? ValueSchema { get; set; }
    public string? KeyType { get; set; }
}

/// <summary>
/// Reflection-based schema generation plus JSON/YAML round-tripping for the configuration GUI.
/// </summary>
public static class ConfigSchema
{
    // Used for the schema and status/test payloads (the frontend reads camelCase keys).
    public static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() },
    };

    // Used for the config payload itself. Keys are the model's real (PascalCase) property names so
    // they line up exactly with the schema's Key values the form binds against.
    private static readonly JsonSerializerOptions ConfigJson = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    /// <summary>Build the schema for the whole configuration model.</summary>
    public static List<SchemaNode> Build() => BuildObject(typeof(Config));

    private static List<SchemaNode> BuildObject(Type type)
    {
        var nodes = new List<SchemaNode>();
        foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!prop.CanRead || !prop.CanWrite)
                continue;

            // Skip properties hidden from JSON (e.g. back-compat aliases) so they don't show in the GUI.
            if (prop.GetCustomAttribute<JsonIgnoreAttribute>() is not null)
                continue;

            nodes.Add(BuildNode(prop));
        }
        return nodes;
    }

    private static SchemaNode BuildNode(PropertyInfo prop)
    {
        var type = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;

        var node = new SchemaNode
        {
            // Key drives the JSON payload + the CR spec; align it with [JsonPropertyName] so the GUI
            // JSON, the Kubernetes CR spec, and the YAML config all share one field vocabulary.
            Key = prop.GetCustomAttribute<JsonPropertyNameAttribute>()?.Name ?? prop.Name,
            // Friendly display title for the GUI: [Display(Name)] wins, else the YAML alias / property name.
            Label = prop.GetCustomAttribute<DisplayAttribute>()?.Name
                ?? prop.GetCustomAttribute<YamlMemberAttribute>()?.Alias
                ?? prop.Name,
            Description = ResolveDescription(prop),
            Required = prop.GetCustomAttribute<RequiredAttribute>() is not null,
        };

        if (prop.GetCustomAttribute<RangeAttribute>() is { } range)
        {
            node.Min = ToDouble(range.Minimum);
            node.Max = ToDouble(range.Maximum);
        }

        if (prop.GetCustomAttribute<DefaultValueAttribute>()?.Value is { } dv)
            node.Default = dv;

        if (prop.GetCustomAttribute<TemplateVariablesAttribute>() is { } tv)
            node.TemplateVars = tv.Names;

        node.Type = ClassifyAndPopulate(type, prop.Name, node);
        return node;
    }

    private static string ClassifyAndPopulate(Type type, string name, SchemaNode node)
    {
        if (type == typeof(string))
            return name.Contains("password", StringComparison.OrdinalIgnoreCase) ? "password" : "string";

        if (type == typeof(bool)) return "bool";
        if (type == typeof(int) || type == typeof(long) || type == typeof(short)) return "int";
        if (type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "double";

        if (type.IsEnum)
        {
            node.EnumValues = Enum.GetNames(type);
            return "enum";
        }

        // Dictionary<TKey, TValue> -> a map of editable rows.
        var dict = type.GetInterfaces().Concat([type])
            .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>));
        if (dict is not null)
        {
            var args = dict.GetGenericArguments();
            node.KeyType = args[0] == typeof(string) ? "string" : "int";
            node.ValueSchema = BuildValueSchema(args[1]);
            return "dictionary";
        }

        // List/array of objects or scalars.
        if (type != typeof(string) && typeof(IEnumerable).IsAssignableFrom(type))
        {
            var elem = type.IsArray ? type.GetElementType()! : type.GetGenericArguments().FirstOrDefault();
            if (elem is not null)
            {
                node.ValueSchema = BuildValueSchema(elem);
                return "list";
            }
        }

        // Nested settings object.
        node.Properties = BuildObject(type);
        return "object";
    }

    private static SchemaNode BuildValueSchema(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        var node = new SchemaNode { Key = "", Label = "" };
        node.Type = ClassifyAndPopulate(type, "", node);
        return node;
    }

    private static string? ResolveDescription(PropertyInfo prop)
        => prop.GetCustomAttribute<YamlMemberAttribute>()?.Description
        ?? prop.GetCustomAttribute<DisplayAttribute>()?.Description
        ?? prop.GetCustomAttribute<DescriptionAttribute>()?.Description;

    private static double? ToDouble(object? value)
        => value is null ? null : Convert.ToDouble(value);

    /// <summary>Serialize the live config to JSON for the form to bind against.</summary>
    public static string ToJson(Config config) => JsonSerializer.Serialize(config, ConfigJson);

    /// <summary>Deserialize the form's JSON back into a config object.</summary>
    public static Config FromJson(string json)
        => JsonSerializer.Deserialize<Config>(json, ConfigJson) ?? throw new Exception("Configuration payload was empty.");

    /// <summary>
    /// Return a deep copy with secrets stripped, for writing to a Kubernetes CR or exporting a manifest
    /// (credentials belong in a Secret, not the CR spec / committed manifest).
    /// </summary>
    public static Config RedactSecrets(Config config)
    {
        var clone = FromJson(ToJson(config));
        clone.MQTT.Credentials = null;
        clone.PDU.Credentials = null;
        clone.EmonCMS.ApiKey = null;
        clone.Gui.Password = null;
        return clone;
    }

    /// <summary>Serialize a config object to YAML (honoring the model's YAML aliases).</summary>
    public static string ToYaml(Config config)
    {
        var serializer = new SerializerBuilder()
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .WithQuotingNecessaryStrings()
            .Build();
        return serializer.Serialize(config);
    }
}
