using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using rPDU2MQTT.Classes;
using YamlDotNet.Serialization;

namespace rPDU2MQTT.Services.Gui;

/// <summary>
/// Describes a single configuration field so the GUI can render a typed input for it.
/// The schema is generated by reflecting over the <see cref="Config"/> model and its
/// YAML/Display/validation attributes, so it stays in sync with the model automatically.
/// </summary>
public sealed class SchemaNode
{
    public string Key { get; set; } = "";
    public string Label { get; set; } = "";
    public string? Description { get; set; }
    public string Type { get; set; } = "string";
    public bool Required { get; set; }
    public object? Default { get; set; }
    public double? Min { get; set; }
    public double? Max { get; set; }
    public string[]? EnumValues { get; set; }
    public List<SchemaNode>? Properties { get; set; }
    public SchemaNode? ValueSchema { get; set; }
    public string? KeyType { get; set; }
}

/// <summary>
/// Reflection-based schema generation plus JSON/YAML round-tripping for the configuration GUI.
/// </summary>
public static class ConfigSchema
{
    public static readonly JsonSerializerOptions Json = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Converters = { new JsonStringEnumConverter() },
    };

    /// <summary>Build the schema for the whole configuration model.</summary>
    public static List<SchemaNode> Build() => BuildObject(typeof(Config));

    private static List<SchemaNode> BuildObject(Type type)
    {
        var nodes = new List<SchemaNode>();
        foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (!prop.CanRead || !prop.CanWrite)
                continue;

            nodes.Add(BuildNode(prop));
        }
        return nodes;
    }

    private static SchemaNode BuildNode(PropertyInfo prop)
    {
        var type = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;

        var node = new SchemaNode
        {
            Key = prop.Name,
            Label = prop.GetCustomAttribute<YamlMemberAttribute>()?.Alias ?? prop.Name,
            Description = ResolveDescription(prop),
            Required = prop.GetCustomAttribute<RequiredAttribute>() is not null,
        };

        if (prop.GetCustomAttribute<RangeAttribute>() is { } range)
        {
            node.Min = ToDouble(range.Minimum);
            node.Max = ToDouble(range.Maximum);
        }

        if (prop.GetCustomAttribute<DefaultValueAttribute>()?.Value is { } dv)
            node.Default = dv;

        node.Type = ClassifyAndPopulate(type, prop.Name, node);
        return node;
    }

    private static string ClassifyAndPopulate(Type type, string name, SchemaNode node)
    {
        if (type == typeof(string))
            return name.Contains("password", StringComparison.OrdinalIgnoreCase) ? "password" : "string";

        if (type == typeof(bool)) return "bool";
        if (type == typeof(int) || type == typeof(long) || type == typeof(short)) return "int";
        if (type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "double";

        if (type.IsEnum)
        {
            node.EnumValues = Enum.GetNames(type);
            return "enum";
        }

        // Dictionary<TKey, TValue> -> a map of editable rows.
        var dict = type.GetInterfaces().Concat([type])
            .FirstOrDefault(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>));
        if (dict is not null)
        {
            var args = dict.GetGenericArguments();
            node.KeyType = args[0] == typeof(string) ? "string" : "int";
            node.ValueSchema = BuildValueSchema(args[1]);
            return "dictionary";
        }

        // List/array of objects or scalars.
        if (type != typeof(string) && typeof(IEnumerable).IsAssignableFrom(type))
        {
            var elem = type.IsArray ? type.GetElementType()! : type.GetGenericArguments().FirstOrDefault();
            if (elem is not null)
            {
                node.ValueSchema = BuildValueSchema(elem);
                return "list";
            }
        }

        // Nested settings object.
        node.Properties = BuildObject(type);
        return "object";
    }

    private static SchemaNode BuildValueSchema(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;
        var node = new SchemaNode { Key = "", Label = "" };
        node.Type = ClassifyAndPopulate(type, "", node);
        return node;
    }

    private static string? ResolveDescription(PropertyInfo prop)
        => prop.GetCustomAttribute<YamlMemberAttribute>()?.Description
        ?? prop.GetCustomAttribute<DisplayAttribute>()?.Description
        ?? prop.GetCustomAttribute<DescriptionAttribute>()?.Description;

    private static double? ToDouble(object? value)
        => value is null ? null : Convert.ToDouble(value);

    /// <summary>Serialize the live config to JSON for the form to bind against.</summary>
    public static string ToJson(Config config) => JsonSerializer.Serialize(config, Json);

    /// <summary>Deserialize the form's JSON back into a config object.</summary>
    public static Config FromJson(string json)
        => JsonSerializer.Deserialize<Config>(json, Json) ?? throw new Exception("Configuration payload was empty.");

    /// <summary>Serialize a config object to YAML (honoring the model's YAML aliases).</summary>
    public static string ToYaml(Config config)
    {
        var serializer = new SerializerBuilder()
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .WithQuotingNecessaryStrings()
            .Build();
        return serializer.Serialize(config);
    }
}
