apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: app
  name: rpdu2mqtt
  namespace: rpdu2mqtt
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rpdu2mqtt
      role: app
  template:
    metadata:
      labels:
        app: rpdu2mqtt
        role: app
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - image: ghcr.io/xtremeownage/rpdu2mqtt:dev-name
        name: app
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          runAsUser: 1654
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: config-files
          mountPath: /config   
        resources:
          limits:
            memory: 800Mi
            cpu: 300m
          requests:
            memory: 100Mi
            cpu: 100m
      volumes:
      - name: config-files
        configMap:
          name: configuration
          defaultMode: 0777
          