#!/bin/bash

# This is just a simple helper script to open a bash-prompt to the container running rpdu2mqtt.

ns="rpdu2mqtt"
kubectl exec -it -n $ns $(kubectl get pod -n $ns -l role=app -o jsonpath='{.items[0].metadata.name}') -- $1

